### ISSUE TITLE
java.io.IOException: last block incomplete in decryption

### ISSUE THREAD

**Issue by rey5137** [VictorAlbertos/ReactiveCache#1]
When using your lib, it give me warnings when try reading from cache:

``` xml
W/System.err: java.io.IOException: last block incomplete in decryption
W/System.err:     at javax.crypto.CipherOutputStream.close(CipherOutputStream.java:138)
W/System.err:     at io.rx_cache.internal.encrypt.BuiltInEncryptor.write(BuiltInEncryptor.java:106)
W/System.err:     at io.rx_cache.internal.encrypt.BuiltInEncryptor.decrypt(BuiltInEncryptor.java:62)
W/System.err:     at io.rx_cache.internal.encrypt.FileEncryptor.decrypt(FileEncryptor.java:52)
W/System.err:     at io.rx_cache.internal.Disk.retrieveRecord(Disk.java:213)
W/System.err:     at io.rx_cache.internal.cache.EvictExpiredRecordsPersistence.startEvictingExpiredRecords(EvictExpiredRecordsPersistence.java:46)
W/System.err:     at io.rx_cache.internal.ProcessorProvidersBehaviour$1.call(ProcessorProvidersBehaviour.java:59)
W/System.err:     at io.rx_cache.internal.ProcessorProvidersBehaviour$1.call(ProcessorProvidersBehaviour.java:57)
W/System.err:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:517)
W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:471)
W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
...
```

Here is the code I used to create ReactiveCache:

``` java
ReactiveCache reactiveCache = new ReactiveCache.Builder()
        .using(application.getFilesDir(), new GsonSpeaker());
```

You can see that I didn't use `encrypt(String)` config.

**Comment by VictorAlbertos** [comment]
HI @rey5137 

Thanks for the feedback ;)

Try the new version and let me know.

`compile 'com.github.VictorAlbertos:ReactiveCache:0.0.2'`
