### ISSUE TITLE
ReactiveCache is crashing when used in project with new version of Dagger2

### ISSUE THREAD

**Issue by AlexTrotsenko** [VictorAlbertos/ReactiveCache#23]
I got following exception/crash when updating dagger2 to the new version.

It might be cause by [this issue](https://github.com/google/dagger/pull/950). And looks very similar to [issue from another project](https://github.com/Polidea/RxAndroidBle/issues/342)

```
      AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.spotme.android, PID: 4817
                         E  java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/Me
                            mbersInjectors; or its super classes (declaration of 'dagger.internal.MembersInjectors' appears in base.apk!classes29.dex)
                         E      at io.rx_cache2.internal.cache.EvictRecord_Factory.get(EvictRecord_Factory.java:36)
                         E      at io.rx_cache2.internal.cache.EvictRecord_Factory.get(EvictRecord_Factory.java:11)
                         E      at io.rx_cache2.internal.cache.TwoLayersCache_Factory.get(TwoLayersCache_Factory.java:33)
                         E      at io.rx_cache2.internal.cache.TwoLayersCache_Factory.get(TwoLayersCache_Factory.java:7)
                         E      at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                         E      at io.rx_cache2.internal.ProcessorProvidersBehaviour_Factory.get(ProcessorProvidersBehaviour_Factory.java:48)
                         E      at io.rx_cache2.internal.ProcessorProvidersBehaviour_Factory.get(ProcessorProvidersBehaviour_Factory.java:11)
                         E      at io.rx_cache2.internal.RxCacheModule_ProvideProcessorProvidersFactory.get(RxCacheModule_ProvideProcessorProvidersFactory.java:30)
                         E      at io.rx_cache2.internal.RxCacheModule_ProvideProcessorProvidersFactory.get(RxCacheModule_ProvideProcessorProvidersFactory.java:8)
                         E      at io.rx_cache2.internal.DaggerRxCacheComponent.providers(DaggerRxCacheComponent.java:202)
                         E      at io.reactivecache2.ReactiveCache.<init>(ReactiveCache.java:39)
                         E      at io.reactivecache2.ReactiveCache.<init>(ReactiveCache.java:30)
                         E      at io.reactivecache2.ReactiveCache$Builder.using(ReactiveCache.java:154)

```

**Comment by AlexTrotsenko** [comment]
@VictorAlbertos looks like changes in https://github.com/VictorAlbertos/RxCache is needed otherwise lib is not usable in newer projects. 

Looks like [shading is mandatory](https://github.com/google/dagger/pull/950#issuecomment-360270413) in the libs. And here is [an example](https://github.com/Polidea/RxAndroidBle/pull/343/commits/e23e015c1fa93f9cb4fbae4a305cfb51defd7035). 

Do you think you will be able to update the lib with needed changes or ?

**Comment by AlexTrotsenko** [comment]
Just to note: after updating to the latest version, which has ["bump libs version"](https://github.com/VictorAlbertos/RxCache/commit/2bd9ca0fc4bf91d3656c3a7d06a0d4479d3c45ac#diff-7ae5a9093507568eabbf35c3b0665732R45) commit - it starts to work. But anyway looks like shading is needed as otherwise the issue could come again in the future. _(also I am not sure how it will affects projects with lower version of the dagger)_

**Comment by VictorAlbertos** [comment]
Feel free to open a PR to improve it 👍
